version: '2'
services:
  app-back_1:
    image: docker-demo:1.0
    hostname: docker-demo-srv01
    ports:
      - 8081:8080
    environment:
      - VERSION_APP=1.0
    networks:
      - app-nextwork

  app-back_2:
    image: docker-demo:2.0
    hostname: docker-demo-srv02
    ports:
      - 8080:8080
    environment:
      - VERSION_APP=2.0
    networks:
      - app-nextwork

networks:
  app-nextwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.163.252.0/16